services:
  db:
    container_name: postgres_database
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    restart: always
    ports:
      - '5454:5432'
